// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Robot.Repository.Entities;

public partial class Log
{
    public int LogId { get; set; }

    public DateTime Timestamp { get; set; }

    public string Action { get; set; }

    public string Details { get; set; }

    public int TaskId { get; set; }

    public virtual Task Task { get; set; }
}