// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Robot.Repository.Entities;

public partial class Operator
{
    public int OperatorId { get; set; }

    public string Name { get; set; }

    public string Shift { get; set; }

    public string ContactInfo { get; set; }
}