// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Robot.Repository.Entities;

public partial class Stamp
{
    public int StampId { get; set; }

    public string Type { get; set; }

    public string Size { get; set; }

    public string InkColor { get; set; }

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}