// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Robot.Repository.Entities;

public partial class Task
{
    public int TaskId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public string Status { get; set; }

    public int RobotId { get; set; }

    public int? StampId { get; set; }

    public int? ProductId { get; set; }

    public virtual ICollection<Log> Logs { get; set; } = new List<Log>();

    public virtual Product Product { get; set; }

    public virtual Robot Robot { get; set; }

    public virtual Stamp Stamp { get; set; }
}